name: CD - Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout app repo
      - name: Checkout app repo
        uses: actions/checkout@v4

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build & push Docker image
      - name: Build & Push Docker image
        env:
          IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/spring-batch-excel
        run: |
          IMAGE_TAG=1.0.${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE:$IMAGE_TAG -t $IMAGE:latest .
          docker push $IMAGE:$IMAGE_TAG
          docker push $IMAGE:latest
          echo "IMAGE_FULL=$IMAGE:$IMAGE_TAG" >> $GITHUB_ENV

      # Step 4: Checkout infra repo
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.INFRA_REPO }}
          token: ${{ secrets.INFRA_REPO_PAT }}

